### ISSUE TITLE
No performance in all three algorithms

### ISSUE THREAD

**Issue by guikarist** [ku2482/fqf-iqn-qrdqn.pytorch#5]
I use the following command to run three algorithms on Pong respectively, but returns are always around -20 (by replacing `<algo>` with `fqf` and so on).
```shell
python train_<algo>.py --cuda --env_id PongNoFrameskip-v4 --seed 0 --config config/<algo>.yaml
```

Is there anything wrong now at master branch (b4928f91d22c80eb7e42aa268da7f64de7491636)?

**Comment by ku2482** [comment]
Hi, @guikarist 

How long did you train algorithms??

Today, I trained FQF for less than three hours at master branch on `PongNoFrameskip-v4`.
( Orange: naive FQF,  Blue: FQF with {multi_step: 3}. )

![スクリーンショット 2020-06-15 16 39 12](https://user-images.githubusercontent.com/37267851/84630447-e55e4500-af26-11ea-84ec-ab7441983e82.png)

It seems that they are learning well.

Actually, my implementation is focused on **the paper's reproducibility** and don't use techniques like n-step returns and Double Q by default.
So, if you want to train algorithms faster, I recommend you to change config as below. (I think multi_step is the most effective.)

```
multi_step: 3
double_q_learning: True
dueling_net: True
```

If you are interested in more efficient algorithm (rather than good final performance), I recommend you to check out policy-based algorithms like PPO.

Please let me know if you still have problems.
Anyway, thank you for asking :)

**Comment by guikarist** [comment]
Thanks for your reply!

Obviously it is the time which made me wrong. I rerun the FQF experiment last night. Through more than 7 hours I got this result:

![image](https://user-images.githubusercontent.com/19543014/84719115-079aa600-afad-11ea-8903-0c73d9f2f3f3.png)

The curve is just like the first part of yours. However, it's a bit too slow. How did you run 5M steps in 3 hours? Was there any parameters modified?

My test environment has 40 CPU cores, 500G memory and 8 Titan V GPU.

**Comment by ku2482** [comment]
Hi, @guikarist 

Let me assure you that GPU is enabled.
Could you check it like below??

```
import torch
print(torch.cuda.is_available())
a = torch.zeros(4)
a.cuda()
print(a.device)
```

If it doesn't use GPUs, please check your CUDA setup. If you're using other than CUDA 10.2, maybe you need to reinstall PyTorch for the proper version of CUDA. Please see [instructions](https://pytorch.org/get-started/locally/) for more details.

Could you report me the result??

**Comment by ku2482** [comment]
BTW, you have really good resources...
I'm kinda jealous lol

**Comment by guikarist** [comment]
These resources are shared among our lab, not belonging to me LOL.

Thanks for your advice, now I got similar results!

![image](https://user-images.githubusercontent.com/19543014/84837424-af29de00-b06a-11ea-9e4e-3ae81333219e.png)

**Comment by THSWind** [comment]
> BTW, you have really good resources...
> I'm kinda jealous lol

Me too,
what a lucky dog!
